services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: compsci
      POSTGRES_DB: notatedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d notatedb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    ports:
      - "4001:4001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:compsci@postgres:5432/notatedb?schema=auth
      - POSTGRES_PASSWORD=compsci
      - GMAIL_USER=notate.demo@gmail.com
      - GMAIL_PASSWORD=hkjwhfykhmkomvda
    stop_signal: SIGTERM
    stop_grace_period: 1s
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4001/health" ]
      interval: 5s
      timeout: 10s
      retries: 3

  class-service:
    container_name: class-service
    build: ./services/class-service
    ports:
      - "4002:4002"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:compsci@postgres:5432/notatedb?schema=class
      - POSTGRES_PASSWORD=compsci
    stop_signal: SIGTERM
    stop_grace_period: 1s
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4002/health" ]
      interval: 5s
      timeout: 10s
      retries: 3

  submission-service:
    container_name: submission-service
    build: ./services/submission-service
    ports:
      - "4003:4003"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:compsci@postgres:5432/notatedb?schema=class
      - POSTGRES_PASSWORD=compsci
    stop_signal: SIGTERM
    stop_grace_period: 1s
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4003/health" ]
      interval: 5s
      timeout: 10s
      retries: 3

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway/
    ports:
      - "4000:4000"
    depends_on:
      auth-service:
        condition: service_healthy
      class-service:
        condition: service_healthy
      submission-service:
        condition: service_healthy
    stop_signal: SIGTERM
    stop_grace_period: 1s

volumes:
  postgres_data:
