services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: compsci
      POSTGRES_DB: notatedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  auth-service:
    container_name: auth-service
    build: ./services/auth-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:compsci@postgres:5432/notatedb?schema=auth
    env_file:
      - ./services/auth-service/.env
    stop_signal: SIGTERM

  class-service:
    container_name: class-service
    build: ./services/class-service
    ports:
      - "4002:4002"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:compsci@postgres:5432/notatedb?schema=class
    env_file:
      - ./services/class-service/.env
    stop_signal: SIGTERM

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway/
    ports:
      - "4000:4000"
    depends_on:
      - auth-service

volumes:
  postgres_data: